/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-13-inch-2020-efab224280fd4c3993c808107f7c0b38
Title: Macbook Pro 13 inch 2020
*/

import { Fragment, JSX, useEffect, useRef, useState } from "react";
import { Html, Text, useGLTF } from "@react-three/drei";
import * as THREE from "three";
import useGlobal from "../Global-State";
import { useFrame } from "@react-three/fiber";

function MacOS() {
  const [showIframe, setShowIframe] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setShowIframe(true), 1000);
    return () => clearTimeout(timer);
  }, []);

  return (
    <Fragment>
      <Html
        transform
        center
        rotation={[1.5755, 0, 0]}
        scale={0.049}
        position={[0.000, 0.35, 0.415]}
      >
        {showIframe && (
          <iframe
            onPointerDown={(e) => e.stopPropagation()}
            src='https://prakhargupta-portfolio.vercel.app'
            style={{
              width: "1200px",
              opacity: 0.85,
              height: "770px",
              border: "none",
              transformOrigin: "top-left",
              borderRadius: ".5rem",
            }}
          />
        )}
      </Html>
    </Fragment>
  );
}

type MacbookGLTF = {
  nodes: Record<`Object_${number}`, THREE.Mesh>;

  materials: {
    Black_Glass: THREE.Material;
    Black_Plastic: THREE.Material;
    Glass: THREE.Material;
    Space_Grey: THREE.Material;
    Camera_Light: THREE.Material;
    ["Keys.001"]: THREE.Material;
    ["Material.001"]: THREE.Material;
    Caps_Lock_Light: THREE.Material;
    ["Space_Grey.001"]: THREE.Material;
    Keys: THREE.Material;
    ["Touch_Bar_Shot_2021-04-02_at_18.13.28"]: THREE.Material;
  };
};

export default function Macbook(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const screenRef = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(
    "/models/macbook.glb"
  ) as unknown as MacbookGLTF;
  const { laptopClicked } = useGlobal();

  const targetRotation = useRef(new THREE.Euler());

  useEffect(() => {
    const openRotation = new THREE.Euler(-Math.PI / 1.9, 0, 0); // Open angle
    const closedRotation = new THREE.Euler(0, 0, 0); // Closed angle

    targetRotation.current.copy(laptopClicked ? openRotation : closedRotation);
  }, [laptopClicked]);

  useFrame(() => {
    if (screenRef.current) {
      screenRef.current.rotation.x = THREE.MathUtils.lerp(
        screenRef.current.rotation.x,
        targetRotation.current.x,
        0.1
      );
    }
  });

  return (
    <Fragment>
      <group
        ref={group}
        {...props}
        dispose={null}
        scale={9.5}
        position={[-0.1, 3, -0.1]}
        rotation={[0, 0.575, 0]}
      >
        <group name='Sketchfab_Scene'>
          <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
            <group name='root'>
              <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
                <group
                  ref={screenRef}
                  name='Bevels_2'
                  rotation={[0, 0, 0]}
                  position={[0, 0.008, -0.104]}
                  scale={0.275}
                >
                  {laptopClicked && <MacOS />}
                  <mesh
                    name='Object_4'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.Black_Glass}
                  />
                  <mesh
                    name='Object_5'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.Black_Plastic}
                  />
                  <mesh
                    name='Object_6'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_6.geometry}
                    material={materials.Glass}
                  >
                    <Text
                      font=''
                      color='white'
                      scale={0.015}
                      position={[0, 0, 0.025]}
                      rotation={[1.6, 0, 0]}
                      anchorX='center'
                      anchorY='middle'
                    >
                      MacBook Air
                    </Text>
                  </mesh>

                  <mesh
                    name='Object_8'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials.Space_Grey}
                  />
                  <mesh
                    name='Object_9'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials["Space_Grey.001"]}
                  />
                  <group
                    name='Empty_1'
                    position={[0, 0.001, 0]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={[-0.039, 0.039, 0.039]}
                  >
                    <group
                      name='Camera_Light_0'
                      position={[0, 0.077, -0.044]}
                      rotation={[-1.192, 0, 0]}
                      scale={[-25.381, 25.381, 25.381]}
                    >
                      <mesh
                        name='Object_12'
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_12.geometry}
                        material={materials.Camera_Light}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name='Caps_Lock_Light_3'
                  position={[0, -0.014, 0]}
                  scale={0.275}
                >
                  <mesh
                    name='Object_14'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials.Caps_Lock_Light}
                  />
                </group>
                <group
                  name='Macbook_Pro_4'
                  position={[0, 0.008, -0.104]}
                  rotation={[1.949, 0, 0]}
                  scale={0.275}
                >
                  <mesh
                    name='Object_16'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials["Material.001"]}
                  />
                </group>
                <group
                  name='Main_Body_5'
                  position={[0, -0.014, 0]}
                  scale={0.275}
                >
                  <mesh
                    name='Object_18'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials.Space_Grey}
                  />
                  <mesh
                    name='Object_19'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials.Black_Plastic}
                  />
                  <mesh
                    name='Object_20'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials.Black_Plastic}
                  />
                  <mesh
                    name='Object_21'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials["Keys.001"]}
                  />
                </group>
                <group
                  name='Touch_Bar_6'
                  position={[0, -0.014, 0]}
                  scale={0.275}
                >
                  <mesh
                    name='Object_23'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials.Black_Plastic}
                  />
                  <mesh
                    name='Object_24'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials.Black_Glass}
                  />
                  <mesh
                    name='Object_25'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials.Keys}
                  />
                </group>
                <group
                  name='Touch_Bar_Shot_7'
                  position={[0, -0.014, 0]}
                  scale={0.275}
                >
                  <mesh
                    name='Object_27'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={
                      materials["Touch_Bar_Shot_2021-04-02_at_18.13.28"]
                    }
                  />
                </group>
                <group
                  name='Keyboard_8'
                  position={[0, -0.014, 0]}
                  scale={0.275}
                >
                  <mesh
                    name='Object_29'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_29.geometry}
                    material={materials.Black_Plastic}
                  />
                  <mesh
                    name='Object_30'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials.Keys}
                  />
                </group>
                <group name='Cube_9' position={[0, -0.014, 0]}>
                  <mesh
                    name='Object_32'
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials.Black_Plastic}
                  />
                </group>
                <group
                  name='Circle001_12'
                  position={[0.203, 0.008, -0.104]}
                  rotation={[0.011, -0.75, 1.274]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </Fragment>
  );
}

useGLTF.preload("/models/macbook.glb");
